# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='bio',
            field=models.TextField(blank=True, default='Instructor', max_length=300),
        ),
        migrations.AlterField(
            model_name='professor',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
