# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190304_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=40),
        ),
    ]
