# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190304_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
