# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_max_students',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_start_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
