# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190312_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(default='Prof Jane', max_length=50),
        ),
    ]
