# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_head', models.CharField(max_length=100)),
                ('dept_capacity', models.IntegerField(default=250)),
                ('dept_details', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(default='+123 4567890', max_length=50)),
                ('email', models.EmailField(default='dept@smart-school.com', max_length=254)),
                ('start_date', models.CharField(default='1998', max_length=100)),
            ],
        ),
    ]
