# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_details',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
